import { ITranslationTable } from "angular-translate";

const resources: ITranslationTable = {
    BalerDisplay: {
        TITLE: "Avangard Baler Controller",
        SettingsDialogButton: "Settings Dialog",
        English: "English",
        Spanish: "Spanish",
        Language: "Language",
    },
    BalerStatsPanel: {
            baleType: "Bale Material",
            lowWeight: "Low Weight",
            currentWeight: "Current Weight",
            highWeight: "High Weight",
    },
    SETTINGS: "Settings",
    CURRENT_BALE_TYPE: "Bale Material",
    REPORT: "Report",
    TRANSER_REPORT: "Bale Event Log",
    LANGUAGE: "Language",
    LOGOUT: "Logout",
    MATERIAL_SETTINGS: "Material Settings",
    WORKER_MANAGEMENT: "Worker Management",
    MACHINE_SETTINGS: "Machine Settings",
    OTHER_SETTINGS: "Other",
    BALER_STATS: "Avangard Bale Monitoring System",
    SETTINGS_MENU: "Settings Menu",
    SELECT_BALE_TYPE: "Select Bale Material:",
    CAMERA_TEST: "Camera Test",
    CAM_UNINIT: "Camera uninitialized.",
    CAM_SUCCESS: "Successfully accessed camera.",
    TAKE_PICTURE: "Take Picture",
    CLOSE: "Close",
    CONFIRM: "Confirm",
    BALER_EMPTIED_CONFIRMATION_TITLE: "Baler Emptied Confirmation",
    TAKING_PICTURE: "Taking Picture",
    PICTURE_TAKEN: "Picture Taken",
    NETWORK_SETTINGS: "Network Settings",
    DIAL_NUM: "Dial Number",
    SET_CAL: "Manually Set Params",
    CALIBRATE: "Calibrate",
    ZERO_BALER: "Take all weight off baler and press next",
    NEXT: "Next",
    BALER_KNOWN_WIEGHT: "Put weight on baler, and enter the weight",
    TEST: "Test",
    CAMERA: "Camera",
    CALIBRATION: "Calibration",
    LAST_BALE_TIME: "Last Bale Time",
    LAST_BALE_WEIGHT: "Last Bale Weight",
    LAST_BALE_MATERIAL: "Last Bale Material",
    ADD: "Add",
    SECURITY: "Security",
    NONE: "None",
    PASSPHRASE: "Passphrase",
    SAVE: "Save",
    PHOTO: "Photo",
    PREVIOUS: "Previous"
};
export = resources;
