import { ITranslationTable } from "angular-translate";

const resources: ITranslationTable = {
    BalerDisplay: {
        TITLE: "El Avangard Baler Controller",
        SettingsDialogButton: "El Settings Dialog",
        English: "El English",
        Spanish: "El Spanish",
        Language: "El Language",
    },
    BalerStatsPanel: {
            baleType: "El Bale Material",
            lowWeight: "El Low Weight",
            currentWeight: "El Current Weight",
            highWeight: "El High Weight",
            weightRange: "El Weight Range",
            CURRENT_WORKER: "El Worker",
    },
    SETTINGS: "El Settings",
    CURRENT_BALE_TYPE: "El Bale Material",
    REPORT: "El Report",
    TRANSER_REPORT: "El Bale Event Log",
    LANGUAGE: "El Language",
    LOGOUT: "El Logout",
    PLEASE_WAIT: "El Loading, please wait...",
    MIN_BALE_DECREASE: "El Bale Event Weight Change (Min): ",
    UPDATE_IMAGE: "El Update Image",
    MATERIAL_SETTINGS: "El Material Settings",
    WORKER_SETTINGS: "El Worker Settings",
    MACHINE_SETTINGS: "El Calibration Settings",
    BALE_EVENT_SETTINGS: "El Bale Event Configuration",
    OTHER_SETTINGS: "El Other",
    BALER_STATS: "El Avangard Bale Monitoring System",
    SETTINGS_MENU: "El Settings Menu",
    SELECT_BALE_TYPE: "El Select Bale Material:",
    CAMERA_TEST: "El Camera Test",
    CAM_UNINIT: "El Camera uninitialized.",
    CAM_SUCCESS: "El Successfully accessed camera.",
    TAKE_PICTURE: "El Take Picture",
    CLOSE: "El Close",
    CONFIRM: "El Confirm",
    CANCEL: "El Cancel",
    CONFIRM_PRINT: "El Confirm & Print",
    BALER_EMPTIED_CONFIRMATION_TITLE: "El Baler Emptied Confirmation",
    TAKING_PICTURE: "El Taking Picture",
    PICTURE_TAKEN: "El Picture Taken",
    NETWORK_SETTINGS: "El Network Settings",
    DIAL_NUM: "El Dial Number",
    SET_CAL: "El Manually Set Params",
    CALIBRATE: "El Calibrate",
    ZERO_BALER: "El Take all weight off baler and press next",
    NEXT: "El Next",
    BALER_KNOWN_WIEGHT: "El Put weight on baler, and enter the weight",
    TEST: "El Test",
    CAMERA: "El Camera",
    CALIBRATION: "El Calibration",
    LAST_BALE_TIME: "El Last Bale Time",
    LAST_BALE_WEIGHT: "El Last Bale Weight",
    LAST_BALE_MATERIAL: "El Last Bale Material",
    ADD: "El Add",
    SECURITY: "El Security",
    NONE: "El None",
    PASSPHRASE: "El Passphrase",
    SAVE: "El Save",
    PHOTO: "El Photo",
    PREVIOUS: "El Previous",
    CUSTOMER_ID_TITLE: "El Environmental Partner ID: ",
    BALER_ID_TITLE: "El Equipment Serial Number: ",
    CUSTOMER_SETTINGS: "El Partner Settings",
    REPRINT: "El Reprint",
};
export = resources;
